from __future__ import annotations

import base64
from collections.abc import Mapping
from dataclasses import dataclass
from io import BytesIO
import logging
import os
import re
from time import time
from typing import Any
import xml.etree.ElementTree as ET
import zipfile

import requests

from app.integrations.dingtalk.openapi_identity import LEGACY_DINGTALK_BASE
from app.schemas.dingtalk_chat import IncomingChatMessage
from app.schemas.reimbursement import ReimbursementAttachmentProcessResult
from app.services.reimbursement_request import ReimbursementAttachmentProcessor

DEFAULT_OPENAPI_ENDPOINT = "https://api.dingtalk.com"
_DEPT_LABEL_PATTERN = re.compile(r"部门[:：]?\s*([^\s,，;；]+)")
_AMOUNT_LABEL_PATTERN = re.compile(r"金额(?:\(元\))?[:：]?\s*([0-9]+(?:\.[0-9]{1,2})?)")
_NUMERIC_PATTERN = re.compile(r"[0-9]+(?:\.[0-9]{1,2})?")


@dataclass(frozen=True)
class ReimbursementAttachmentSettings:
    enabled: bool
    openapi_endpoint: str
    legacy_openapi_endpoint: str
    upload_media_type: str


class DingTalkReimbursementAttachmentProcessor(ReimbursementAttachmentProcessor):
    def __init__(
        self,
        *,
        client_id: str,
        client_secret: str,
        settings: ReimbursementAttachmentSettings,
        timeout_seconds: float = 10.0,
        logger: logging.Logger | None = None,
    ) -> None:
        self._client_id = client_id.strip()
        self._client_secret = client_secret.strip()
        self._settings = settings
        self._timeout_seconds = timeout_seconds
        self._logger = logger or logging.getLogger("keagent.observability")
        self._access_token = ""
        self._access_token_expires_at = 0.0

    def process(
        self,
        *,
        message: IncomingChatMessage,
        conversation_id: str,
        sender_id: str,
    ) -> ReimbursementAttachmentProcessResult:
        del conversation_id, sender_id
        if not self._settings.enabled:
            return ReimbursementAttachmentProcessResult(
                success=False,
                reason="附件处理能力未启用，请联系管理员检查配置。",
            )

        file_bytes = self._resolve_file_bytes(message=message)
        if not file_bytes:
            return ReimbursementAttachmentProcessResult(
                success=False,
                reason="未获取到Excel文件内容，请重新上传。",
            )

        department, amount = self._parse_xlsx_department_and_amount(file_bytes=file_bytes)
        if not department:
            return ReimbursementAttachmentProcessResult(
                success=False,
                reason="未识别到部门，请检查报销单模板后重传。",
            )
        if not amount:
            return ReimbursementAttachmentProcessResult(
                success=False,
                reason="未识别到金额，请检查报销单模板后重传。",
            )

        pdf_bytes = self._build_pdf_bytes(
            lines=(
                "Travel Reimbursement Summary",
                f"Department: {department}",
                f"Amount: {amount}",
                "Generated by Ke Agent",
            )
        )
        media_id = self._upload_pdf_and_get_media_id(pdf_bytes=pdf_bytes)
        if not media_id:
            return ReimbursementAttachmentProcessResult(
                success=False,
                reason="附件上传失败，请稍后重试。",
            )

        return ReimbursementAttachmentProcessResult(
            success=True,
            reason="processed",
            department=department,
            amount=amount,
            attachment_media_id=media_id,
        )

    def _resolve_file_bytes(self, *, message: IncomingChatMessage) -> bytes:
        encoded = (message.file_content_base64 or "").strip()
        if encoded:
            try:
                return base64.b64decode(encoded)
            except Exception:
                self._logger.warning("reimbursement.attachment.base64_decode_failed")
        download_url = (message.file_download_url or "").strip()
        if download_url:
            try:
                response = requests.get(download_url, timeout=self._timeout_seconds)
                response.raise_for_status()
                return bytes(response.content or b"")
            except requests.RequestException:
                self._logger.exception("reimbursement.attachment.download_failed")
                return b""
        return b""

    def _parse_xlsx_department_and_amount(self, *, file_bytes: bytes) -> tuple[str, str]:
        try:
            rows = _extract_xlsx_rows(file_bytes=file_bytes)
        except Exception:
            self._logger.exception("reimbursement.attachment.xlsx_parse_failed")
            return "", ""
        return _extract_department_and_amount_from_rows(rows=rows)

    def _upload_pdf_and_get_media_id(self, *, pdf_bytes: bytes) -> str:
        if not pdf_bytes:
            return ""
        try:
            access_token = self._get_access_token()
            response = requests.post(
                f"{self._settings.legacy_openapi_endpoint}/media/upload",
                params={"access_token": access_token, "type": self._settings.upload_media_type},
                files={"media": ("travel_reimbursement.pdf", pdf_bytes, "application/pdf")},
                timeout=self._timeout_seconds,
            )
            response.raise_for_status()
            payload = response.json()
        except requests.RequestException:
            self._logger.exception("reimbursement.attachment.media_upload_failed")
            return ""
        except ValueError:
            self._logger.exception("reimbursement.attachment.media_upload_invalid_json")
            return ""
        return str(payload.get("media_id") or payload.get("mediaId") or "").strip()

    def _get_access_token(self) -> str:
        now = time()
        if self._access_token and now < self._access_token_expires_at:
            return self._access_token

        response = requests.post(
            f"{self._settings.openapi_endpoint}/v1.0/oauth2/accessToken",
            headers={"Content-Type": "application/json", "Accept": "application/json"},
            json={"appKey": self._client_id, "appSecret": self._client_secret},
            timeout=self._timeout_seconds,
        )
        response.raise_for_status()
        payload = response.json()
        access_token = str(payload.get("accessToken") or "").strip()
        expire_in = int(payload.get("expireIn") or 7200)
        if not access_token:
            raise RuntimeError("OpenAPI access token is empty")
        self._access_token = access_token
        self._access_token_expires_at = time() + max(expire_in - 300, 60)
        return self._access_token

    @staticmethod
    def _build_pdf_bytes(*, lines: tuple[str, ...]) -> bytes:
        text_lines = [line.strip() for line in lines if line.strip()]
        if not text_lines:
            text_lines = ["Ke Agent Reimbursement Attachment"]

        content_ops = ["BT", "/F1 12 Tf", "50 780 Td"]
        for index, line in enumerate(text_lines):
            if index > 0:
                content_ops.append("0 -18 Td")
            safe_line = (
                line.encode("latin-1", "replace")
                .decode("latin-1")
                .replace("\\", "\\\\")
                .replace("(", "\\(")
                .replace(")", "\\)")
            )
            content_ops.append(f"({safe_line}) Tj")
        content_ops.append("ET")
        stream = "\n".join(content_ops).encode("latin-1", "replace")

        objects = [
            b"1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
            b"2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
            b"3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 5 0 R /Resources << /Font << /F1 4 0 R >> >> >> endobj",
            b"4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
            b"5 0 obj << /Length %d >> stream\n%s\nendstream endobj" % (len(stream), stream),
        ]

        out = BytesIO()
        out.write(b"%PDF-1.4\n")
        offsets = [0]
        for obj in objects:
            offsets.append(out.tell())
            out.write(obj)
            out.write(b"\n")
        xref_start = out.tell()
        out.write(f"xref\n0 {len(offsets)}\n".encode("latin-1"))
        out.write(b"0000000000 65535 f \n")
        for offset in offsets[1:]:
            out.write(f"{offset:010d} 00000 n \n".encode("latin-1"))
        out.write(
            (
                f"trailer << /Size {len(offsets)} /Root 1 0 R >>\n"
                f"startxref\n{xref_start}\n%%EOF"
            ).encode("latin-1")
        )
        return out.getvalue()


def _extract_xlsx_rows(*, file_bytes: bytes) -> list[list[str]]:
    with zipfile.ZipFile(BytesIO(file_bytes)) as zf:
        shared_strings = _load_shared_strings(zf)
        worksheet_path = _pick_first_sheet_path(zf)
        with zf.open(worksheet_path) as fp:
            tree = ET.parse(fp)
    root = tree.getroot()
    ns = {"s": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
    rows: list[list[str]] = []
    for row in root.findall(".//s:sheetData/s:row", ns):
        values: list[str] = []
        for cell in row.findall("s:c", ns):
            value = _extract_cell_value(cell=cell, shared_strings=shared_strings, ns=ns)
            values.append(value)
        if any(item.strip() for item in values):
            rows.append(values)
    return rows


def _load_shared_strings(zf: zipfile.ZipFile) -> list[str]:
    if "xl/sharedStrings.xml" not in zf.namelist():
        return []
    with zf.open("xl/sharedStrings.xml") as fp:
        tree = ET.parse(fp)
    ns = {"s": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
    values: list[str] = []
    for item in tree.getroot().findall(".//s:si", ns):
        text_nodes = item.findall(".//s:t", ns)
        text = "".join(node.text or "" for node in text_nodes).strip()
        values.append(text)
    return values


def _pick_first_sheet_path(zf: zipfile.ZipFile) -> str:
    sheet_paths = sorted(name for name in zf.namelist() if name.startswith("xl/worksheets/sheet") and name.endswith(".xml"))
    if not sheet_paths:
        raise ValueError("xlsx worksheet is missing")
    return sheet_paths[0]


def _extract_cell_value(*, cell: ET.Element, shared_strings: list[str], ns: dict[str, str]) -> str:
    cell_type = (cell.attrib.get("t") or "").strip()
    value_node = cell.find("s:v", ns)
    inline_node = cell.find("s:is/s:t", ns)
    if inline_node is not None and inline_node.text:
        return inline_node.text.strip()
    if value_node is None or value_node.text is None:
        return ""
    raw = value_node.text.strip()
    if cell_type == "s":
        try:
            index = int(raw)
        except ValueError:
            return raw
        if 0 <= index < len(shared_strings):
            return shared_strings[index].strip()
        return raw
    return raw


def _extract_department_and_amount_from_rows(*, rows: list[list[str]]) -> tuple[str, str]:
    department = ""
    amount = ""
    for row in rows:
        compact_row = " ".join(item.strip() for item in row if item.strip())
        if not department:
            department = _extract_department_from_row(row=row, compact_text=compact_row)
        if not amount:
            amount = _extract_amount_from_row(row=row, compact_text=compact_row)
        if department and amount:
            break
    return department, amount


def _extract_department_from_row(*, row: list[str], compact_text: str) -> str:
    match = _DEPT_LABEL_PATTERN.search(compact_text)
    if match:
        return match.group(1).strip()
    for index, value in enumerate(row):
        normalized = value.strip()
        if normalized in {"部门", "所属部门"} and index + 1 < len(row):
            candidate = row[index + 1].strip()
            if candidate:
                return candidate
    return ""


def _extract_amount_from_row(*, row: list[str], compact_text: str) -> str:
    match = _AMOUNT_LABEL_PATTERN.search(compact_text)
    if match:
        return match.group(1).strip()
    for index, value in enumerate(row):
        normalized = value.strip()
        if normalized in {"金额", "金额(元)"} and index + 1 < len(row):
            next_value = row[index + 1].strip()
            numeric = _NUMERIC_PATTERN.search(next_value)
            if numeric:
                return numeric.group(0).strip()
    numeric = _NUMERIC_PATTERN.search(compact_text)
    if numeric:
        return numeric.group(0).strip()
    return ""


def load_reimbursement_attachment_settings(raw_env: Mapping[str, str] | None = None) -> ReimbursementAttachmentSettings:
    env = raw_env if raw_env is not None else os.environ
    enabled = str(env.get("DINGTALK_REIMBURSE_APPROVAL_ENABLED") or "").strip().lower() in {
        "1",
        "true",
        "yes",
        "y",
        "on",
    }
    openapi_endpoint = str(env.get("DINGTALK_OPENAPI_ENDPOINT") or DEFAULT_OPENAPI_ENDPOINT).strip()
    legacy_openapi_endpoint = str(env.get("DINGTALK_LEGACY_OPENAPI_ENDPOINT") or LEGACY_DINGTALK_BASE).strip()
    media_type = str(env.get("DINGTALK_REIMBURSE_ATTACHMENT_MEDIA_TYPE") or "file").strip() or "file"
    return ReimbursementAttachmentSettings(
        enabled=enabled,
        openapi_endpoint=openapi_endpoint.rstrip("/") or DEFAULT_OPENAPI_ENDPOINT,
        legacy_openapi_endpoint=legacy_openapi_endpoint.rstrip("/") or LEGACY_DINGTALK_BASE,
        upload_media_type=media_type,
    )


def build_default_reimbursement_attachment_processor(
    raw_env: Mapping[str, str] | None = None,
    *,
    logger: logging.Logger | None = None,
) -> ReimbursementAttachmentProcessor | None:
    env = raw_env if raw_env is not None else os.environ
    settings = load_reimbursement_attachment_settings(env)
    if not settings.enabled:
        return None
    client_id = str(env.get("DINGTALK_CLIENT_ID") or "").strip()
    client_secret = str(env.get("DINGTALK_CLIENT_SECRET") or "").strip()
    if not client_id or not client_secret:
        obs_logger = logger or logging.getLogger("keagent.observability")
        obs_logger.warning(
            "reimbursement attachment processor disabled: missing DINGTALK_CLIENT_ID or DINGTALK_CLIENT_SECRET"
        )
        return None
    return DingTalkReimbursementAttachmentProcessor(
        client_id=client_id,
        client_secret=client_secret,
        settings=settings,
        logger=logger,
    )
