from __future__ import annotations

from app.schemas.knowledge import KnowledgeEntry

SAMPLE_KNOWLEDGE_VERSION = "a08-sample-v1"


def load_sample_entries() -> tuple[KnowledgeEntry, ...]:
    return (
        KnowledgeEntry(
            source_id="doc-policy-banquet-2026-01",
            source_type="document",
            title="行政制度：商务宴请标准（2026-01）",
            summary="商务宴请标准为人均 300 元；超过标准需提前审批。",
            applicability="适用于对外商务接待和客户宴请场景。",
            next_step="如金额超标，请在钉钉审批中提交“宴请超标说明”。",
            source_uri="钉盘/行政制度/商务宴请标准-2026-01",
            updated_at="2026-01-15",
            keywords=("宴请", "标准", "制度", "商务", "接待", "人均", "300"),
            intents=("policy_process", "other"),
        ),
        KnowledgeEntry(
            source_id="doc-policy-finance-2026-02",
            source_type="document",
            title="财务制度：费用报销总则（2026-02）",
            summary="报销须提供合规发票、行程证明和审批单，超期需补充说明。",
            applicability="适用于差旅、业务招待和办公采购费用报销。",
            next_step="先确认票据完整性，再进入钉钉“费用报销”流程提交。",
            source_uri="钉盘/财务制度/费用报销总则-2026-02",
            updated_at="2026-02-10",
            keywords=("财务", "制度", "报销", "发票", "票据", "总则", "费用"),
            intents=("policy_process", "other"),
        ),
        KnowledgeEntry(
            source_id="doc-process-leave-2026-01",
            source_type="document",
            title="流程说明：请假办理指引（2026-01）",
            summary="请假需按假别提交申请，病假需补充证明材料。",
            applicability="适用于年假、病假、事假和调休申请场景。",
            next_step="进入钉钉“请假审批”模板，按假别填写并上传材料。",
            source_uri="钉盘/流程说明/请假办理指引-2026-01",
            updated_at="2026-01-20",
            keywords=("请假", "流程", "入口", "病假", "年假", "调休", "审批"),
            intents=("policy_process", "leave", "other"),
        ),
        KnowledgeEntry(
            source_id="doc-process-reimbursement-2026-02",
            source_type="document",
            title="流程说明：出差报销操作手册（2026-02）",
            summary="出差报销需要行程单、发票和审批单，提交后由财务复核。",
            applicability="适用于国内外出差费用报销。",
            next_step="在钉钉“费用报销”模板填写行程并上传票据。",
            source_uri="钉盘/流程说明/出差报销操作手册-2026-02",
            updated_at="2026-02-18",
            keywords=("出差", "报销", "流程", "发票", "行程", "审批", "手册"),
            intents=("policy_process", "reimbursement", "other"),
        ),
        KnowledgeEntry(
            source_id="doc-policy-access-2026-03",
            source_type="document",
            title="行政制度：门禁与访客管理规范（2026-03）",
            summary="访客需提前登记，门禁权限申请需部门负责人审批。",
            applicability="适用于员工门禁权限开通与访客接待。",
            next_step="在钉钉提交“门禁权限申请”并抄送行政。",
            source_uri="钉盘/行政制度/门禁与访客管理规范-2026-03",
            updated_at="2026-03-01",
            keywords=("门禁", "访客", "规范", "权限", "行政", "审批", "登记"),
            intents=("policy_process", "other"),
        ),
        KnowledgeEntry(
            source_id="faq-quote-fuser-xx-2026-03",
            source_type="faq",
            title="固定报价 FAQ：XX 定影器",
            summary="XX 定影器标准报价 1200 元/台（含税）。",
            applicability="仅适用于标准维保合同内型号 XX 定影器。",
            next_step="非标准项目请联系商务二次确认。",
            source_uri="FAQ/报价/XX定影器",
            updated_at="2026-03-05",
            keywords=("xx定影器", "定影器", "报价", "多少钱", "价格", "1200"),
            intents=("fixed_quote", "other"),
        ),
        KnowledgeEntry(
            source_id="faq-quote-kit-a1-2026-03",
            source_type="faq",
            title="固定报价 FAQ：A1 维护套件",
            summary="A1 维护套件标准报价 680 元/套（含税）。",
            applicability="适用于 A1 系列标准配件替换场景。",
            next_step="非标准数量折扣请联系商务确认。",
            source_uri="FAQ/报价/A1维护套件",
            updated_at="2026-03-05",
            keywords=("a1", "维护套件", "报价", "价格", "680", "多少钱"),
            intents=("fixed_quote", "other"),
        ),
        KnowledgeEntry(
            source_id="faq-quote-drum-b2-2026-03",
            source_type="faq",
            title="固定报价 FAQ：B2 鼓组件",
            summary="B2 鼓组件标准报价 950 元/套（含税）。",
            applicability="仅适用于 B2 标准机型维护场景。",
            next_step="如需加急交付，请同步商务确认交期。",
            source_uri="FAQ/报价/B2鼓组件",
            updated_at="2026-03-05",
            keywords=("b2", "鼓组件", "报价", "价格", "950", "多少钱"),
            intents=("fixed_quote", "other"),
        ),
        KnowledgeEntry(
            source_id="faq-policy-entry-2026-02",
            source_type="faq",
            title="FAQ：制度文档入口说明",
            summary="制度类文档统一维护在钉盘“制度中心”目录。",
            applicability="适用于常见制度入口查询。",
            next_step="若目录无权限，请联系人事或行政开通。",
            source_uri="FAQ/制度/入口说明",
            updated_at="2026-02-28",
            keywords=("制度", "入口", "在哪里看", "钉盘", "制度中心"),
            intents=("policy_process", "other"),
        ),
        KnowledgeEntry(
            source_id="faq-reimburse-materials-2026-02",
            source_type="faq",
            title="FAQ：报销材料清单",
            summary="差旅报销需发票、行程单和审批通过截图。",
            applicability="适用于标准差旅报销预检查。",
            next_step="若缺少材料，请先补齐后再提交报销。",
            source_uri="FAQ/财务/报销材料清单",
            updated_at="2026-02-28",
            keywords=("报销", "材料", "发票", "行程单", "清单"),
            intents=("policy_process", "reimbursement", "other"),
        ),
    )
